services:
  db:
    image: postgres:16-alpine
    container_name: tp05-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
volumes:
  db_data:
